version: "2"

services:
  nginx-front:
    image: nginx
    volumes:
      - ./nginx-front.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - maintenance
    environment:
      VIRTUAL_HOST: 'domain.example.com'
      LETSENCRYPT_HOST: 'domain.example.com'
      LETSENCRYPT_EMAIL: 'username@domain.example.com'

  app:
    image: nginx
    volumes:
      - ./app.html:/usr/share/nginx/html/index.html

  maintenance:
    image: nginx
    volumes:
      - ./HeroWPCountdown:/usr/share/nginx/html
      - ./maintenance.conf:/etc/nginx/conf.d/default.conf

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - 'le_certs:/etc/nginx/certs'

  letsencrypt-nginx-proxy-companion:
    container_name: 'nginx-letsencrypt'
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"

volumes:
  le_certs:
